version: '3'
services: 
  app:
    container_name: meme
    restart: always
    build: .
    ports:
      - '8081:8081'
    links:
      - mongo
  mongo:
    container_name: localhost
    image: mongo
    ports:
      - '27017:27017'